project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('support/', include('tools.urls')),
]

project/tools/urls.py
from . import views
from django.urls import path
app_name = 'tools'

urlpatterns = [
    path("reset/cloud", views.cloudByKey, name="cloud"),
    path("reset/pro", views.proByDate, name="pro"),
    path("calculate-energy", views.calculate_energy, name="pro")
    
]

project/tools/models.py
from django.db import models

# Create your models here.

project/tools/views.py
from django.shortcuts import render
import json
from bs4 import BeautifulSoup as bs
import requests
import datetime
from django.contrib.auth.decorators import login_required



# Create your views here.
#@login_required(login_url='user:login')
def cloudByKey(request):
    if request.method == "POST":
        xm = request.POST['xm']
        url = requests.post(
            f'https://tools.xmeye.net/deviceSuperPassword?text={xm}')
        html = bs(url.content, 'html.parser')
        dict = json.loads(html.get_text())
        return render(request, 'tools/cloud.html', {"dict":dict})

    return render(request, 'tools/cloud.html')

#@login_required(login_url='user:login')
def proByDate(request):
    day = datetime.datetime.now()
    return render(request, 'tools/pro.html', {"day":day})

def calculate_energy(voltage, current):
    """
    Розраховує кількість енергії в ватт-годинах (Wh)
    на основі значень напруги (вольтажу) та сили струму (амперажу).
    
    Параметри:
    voltage (float): Напруга (вольтах).
    current (float): Сила струму (амперах).
    
    Повертає:
    float: Кількість енергії в ватт-годинах (Wh).
    """
    energy = voltage * current
    return energy

project/tools/templates/include/sidebar.html
{% load static %}

<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
    <a href="#"
        class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <img src="{% static 'tools/img/logo.jpg' %}" class="rounded mx-" width="40" height="32" alt="">
        <span class="fs-4 fw-bold">Partizan UA</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="#" class="btn btn-outline-dark border-0 btn-lg" aria-current="page">
                Домашня сторінка
            </a>
        </li>
        <li>
            <a href="{% url 'tools:cloud' %}" class="btn btn-outline-dark border-0 btn-lg">
                Cloud series
            </a>
        </li>
        <li>
            <a href="{% url 'tools:pro' %}" class="btn btn-outline-dark border-0 btn-lg">
                PRO series
            </a>
        </li>
    </ul>
    <hr>
</div>

<div class="b-example-divider b-example-vr"></div>

project/tools/templates/include/user-sidebar.html
{% load static %}

<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
    <a href="{% url 'article:index' %}"
        class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <img src="{% static 'tools/img/logo.jpg' %}" class="rounded mx-" width="40" height="32" alt="">
        <span class="fs-4 fw-bold">Partizan UA</span>
    </a>
    <hr>
    {% if request.user.is_authenticated %}
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'article:index' %}" class="btn btn-outline-dark border-0 btn-lg" aria-current="page">
                Домашня сторінка
            </a>
        </li>
        <li>
            <a class="btn btn-outline-dark border-0 btn-lg" data-toggle="list" href="#account" role="tab"
            aria-selected="false">
                Акаунт
            </a>
        </li>
        <li>
            <a class="btn btn-outline-dark border-0 btn-lg" data-toggle="list" href="#password" role="tab"
            aria-selected="false">
                Змінити пароль
            </a>
        </li>
        <li>
            <a href="#" class="btn btn-outline-dark border-0 btn-lg">
                Написати статтю
            </a>
        </li>
        <li>
            <a href="#" class="btn btn-outline-dark border-0 btn-lg">
                Мої статті
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">

        <a href="{% url 'user:logout' %}" class=" link-dark text-decoration-none" data-bs-toggle="dropdown"
            aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>Вихід</strong>
        </a>
        {% endif %}
    </div>
</div>

<div class="b-example-divider b-example-vr"></div>



project/tools/templates/tools/calculate.html
{% extends 'tools/layout.html' %}
{%block title%}HDD calculate{%endblock title%}
{% load static %}

{% block content %}

<link rel="shortcut icon" href="{% static 'tools/fast.ico' %}">
<link href="{% static 'tools/css/app.332caf93ad336a1aea5aec3abc91c657.css ' %}"  rel=stylesheet>
<div class="container text-center">
    <div id=app></div>
    <script type=text/javascript src="{% static 'tools/js/manifest.3092b32052a63aba333d.js' %}"></script>
    <script type=text/javascript src="{% static 'tools/js/vendor.fe4431bd75d7efca6f37.js' %}"></script>
    <script type=text/javascript src="{% static 'tools/js/app.2ab392f6f6f774b4bb7f.js' %}"></script>
</div>
{% endblock %}

project/tools/templates/tools/cloud.html
{% extends 'tools/layout.html' %}
{%block title%}Cloud{%endblock title%}


{% block content %}

<div class="container text-center">
    <div class="row justify-content-center py-2">
        <div class="col py-2">
            <h1>Генератор серії Cloud(XM)</h1>
        </div>
        <div class=" row row-cols-3 justify-content-center p-3">
            <div class="col p-3 ">
                <form action="{% url 'tools:cloud' %}" method="post" class="form-control border-none p-2">
                    {% csrf_token %}
                    <p class="form-text col-form-label">Введіть ключ для генерації: <input class="form-control " type="tel" pattern="[0-9]{8-10}"
                            placeholder="52546985 or 20201231(YY:mm:dd)" name="xm" /required>
                    <p class="form-text text-muted">Дата або 8-ми значний ключ.</p>
                    </p>
                    <input type="hidden" name="hidden_field" value="sdgsdfg6656dffgkzsqrc682gbd">
                    <b class="d-flex justify-content-center p-2"><input class="btn btn-dark" type="submit"
                            value="Generate code"></p></b>
                </form>
            </div>
            <div class="col p-2">
                {% if request.POST %}
                <p class="p-2 m-2">Скидання по даті: {{dict.before20161122}}
                <p class="text-muted">Для девайсів до 2016/11/22 візьміть перші 6 символів.</p>
                </p>
                <p class="p-2">Скидання по ключу: {{dict.securityCode}}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/tools/templates/tools/layout.html
<!doctype html>
{% load static %}
<html lang="uk">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors, Alexbrob">
    <meta name="generator" content="Hugo 0.108.0">
    <link href="{% static 'tools/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'tools/css/sidebars.css' %}" rel="stylesheet">
    <link href="{% static 'tools/img/favicon.ico' %}" rel="icon">
    <title>{%block title%}{%endblock title%}</title>
</head>

<body>

    <main class="d-flex flex-nowrap">
        {% include 'include/sidebar.html'%}
        {% block content%}
        {% endblock content %}
    </main>

</body>


</html>

project/tools/templates/tools/pro.html
{% extends 'tools/layout.html' %}
{% load static %}
{%block title%}Pro{%endblock title%}


{% block content %}

<div class="container text-center">
    <div class="row justify-content-center py-2">
        <div class="col py-2">
            <h1>Генератор супер паролю PRO серії</h1>
        </div>
        <div class=" row row-cols-3 justify-content-center p-3">
            <div class="col p-3 ">
                <div class="content">
                    <h5 class="py-2">Введіть дату на реєстраторі</h5>

                    <div class="input-group input-group-lg">
                        <span class="input-group-text" id="inputGroup-sizing-lg">День:</span>
                        <input type="text" class="form-control"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="day" maxlength="2"
                            placeholder="{{ day.day }}"/>
                    </div>

                    <div class="input-group input-group-lg">
                        <span class="input-group-text" id="inputGroup-sizing-lg">Місяць:</span>
                        <input type="text" class="form-control"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="month" maxlength="2"
                            placeholder="{{ day.month }}" />
                    </div>

                    <div class="input-group input-group-lg">
                        <span class="input-group-text" id="inputGroup-sizing-lg">Рік:</span>
                        <input type="text" class="form-control" onkeypress='return event.charCode >= 48 && event.charCode <= 57'
                            id="year" maxlength="4" placeholder="{{ day.year }}" />
                    </div>

                    <div class="col py-4">
                        <input type="submit" onClick="superpassword();" class="button btn btn-dark">
                    </div>
                    <div id="KQ" style="color:red;"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'tools/js/func_pro.js' %}"></script>
    {% endblock %}